// Pins every song in js/data/songs.js to an iTunes track id so the game can fetch previews
// for a whole game in one lookup request.  Run after adding songs:  npm run resolve-songs
//   --all   re-resolve songs that already have an id
import { writeFile } from 'node:fs/promises';
import { SONGS } from '../js/data/songs.js';
import { ITUNES_IDS } from '../js/data/itunesIds.js';
import { findTrack } from '../js/core/itunes.js';

const redoAll = process.argv.includes('--all');
const result = redoAll ? {} : { ...ITUNES_IDS };
const todo = SONGS.filter((s) => !s.previewUrl && (redoAll || !result[s.id]));
const failed = [];
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

console.log(`Resolving ${todo.length} of ${SONGS.length} songs…`);
let done = 0;
async function worker(queue) {
  while (queue.length) {
    const song = queue.shift();
    const countries = song.country === 'IN' || song.country === 'PK' ? ['IN', 'US'] : ['US', 'GB'];
    let attempt = 0;
    while (true) {
      try {
        let match = null;
        let store = null;
        for (const c of countries) {
          match = await findTrack(song, { countries: [c] });
          if (match) { store = c; break; }
        }
        if (match) result[song.id] = [match.trackId, store];
        else failed.push(song);
        break;
      } catch (err) {
        if (err.code === 'RATE_LIMITED' && attempt++ < 8) { await sleep(30000); continue; }
        failed.push(song);
        console.warn(`  ! ${song.title}: ${err.message}`);
        break;
      }
    }
    done++;
    await sleep(1500); // stay under Apple's ~20 requests/minute guidance
    if (done % 25 === 0) console.log(`  ${done}/${todo.length}`);
  }
}

const queue = [...todo];
await worker(queue);

const ordered = Object.keys(result).map(Number).sort((a, b) => a - b);
const body = ordered.map((id) => `  ${id}: [${result[id][0]}, '${result[id][1]}'],`).join('\n');
await writeFile(
  new URL('../js/data/itunesIds.js', import.meta.url),
  `// Generated by \`npm run resolve-songs\` — song id → [iTunes track id, store country].\n` +
    `// Safe to edit by hand: to fix a wrong match, replace the track id with the right one.\n` +
    `export const ITUNES_IDS = {\n${body}\n};\n`,
);

console.log(`\nPinned ${ordered.length} songs.`);
if (failed.length) {
  console.log(`No confident match for ${failed.length}:`);
  failed.forEach((s) => console.log(`  #${s.id} ${s.title} — ${s.artist}`));
  process.exitCode = 1;
}
